# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp0AvWSFvncAUOBesprSVodIb-swnERY
"""

import streamlit as st
import pandas as pd

# ----------------------------------------
# Helper function: compute the blended forward price
# ----------------------------------------
def calc_hedge(df: pd.DataFrame, spot_rate: float):
    df = df.copy()
    # Calculate outright forward rates
    df['Outright']     = spot_rate + df['ForwardPts']
    # Total notional and guard against zero
    total_notional     = df['Notional'].sum()
    if total_notional == 0:
        raise ValueError("Total notional is zero. Enter at least one positive Notional.")
    # Weights and contributions
    df['Weight']       = df['Notional'] / total_notional
    df['Contribution'] = df['Outright'] * df['Weight']
    # Blended forward price
    blended = df['Contribution'].sum()
    return blended, df

# ----------------------------------------
# Page config & header
# ----------------------------------------
st.set_page_config(page_title="FX Hedge Calculator", layout="wide")
st.title("🛡️ Client Exposure Hedge Calculator")

# ----------------------------------------
# Sidebar inputs
# ----------------------------------------
st.sidebar.header("Inputs")
uploaded = st.sidebar.file_uploader("1) Upload exposures CSV", type=["csv"])
spot     = st.sidebar.number_input("2) Spot Rate", value=1.000000, format="%.6f")

# ----------------------------------------
# Main area
# ----------------------------------------
if not uploaded:
    st.info("Please upload a CSV with columns: Expiry, Notional, ForwardPts, Direction")
else:
    try:
        df = pd.read_csv(uploaded, parse_dates=['Expiry'])
    except Exception as e:
        st.error(f"Error reading CSV: {e}")
    else:
        # Validate required columns
        required = {'Expiry', 'Notional', 'ForwardPts', 'Direction'}
        missing  = required - set(df.columns)
        if missing:
            st.error(f"Missing columns: {', '.join(missing)}")
        else:
            try:
                blended, result = calc_hedge(df, spot)
            except Exception as e:
                st.error(f"Calculation error: {e}")
            else:
                # Display blended price
                st.metric("Blended Hedge Price", f"{blended:.6f}")
                # Show full result table
                st.table(result)
                # Build and show trade instructions
                trade_df = result[['Expiry','Direction','Notional','Outright']].copy()
                trade_df.rename(columns={'Outright':'Rate'}, inplace=True)
                st.markdown("#### Trade Instructions")
                st.table(trade_df)
                # Optional: per-expiry contributions chart
                st.markdown("#### Per-expiry Contributions")
                st.bar_chart(
                    result.set_index('Expiry')['Contribution'],
                    use_container_width=True
                )

